@extends('layouts.app')
@section('title','Leads | AI Receptionist')
@section('page_title','Leads')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Leads</h2><p class="text-muted mb-0">Track opportunities generated by the sales engine.</p></div><a href="{{ route('leads.create') }}" class="btn btn-dark">+ Add Lead</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm"><div class="card-body p-0">
@if($leads->count())
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="px-4">Lead</th><th>Company</th><th>Contact</th><th>Status</th><th>Score</th><th>Next Follow-up</th><th class="text-end px-4">Actions</th></tr></thead><tbody>
@foreach($leads as $lead)<tr><td class="px-4"><div class="fw-semibold">{{ $lead->title }}</div><small class="text-muted">{{ ucfirst($lead->source ?: 'Manual') }}</small></td><td><a href="{{ route('companies.show',$lead->company) }}">{{ $lead->company->name }}</a></td><td>{{ $lead->contact ? $lead->contact->first_name.' '.$lead->contact->last_name : '—' }}</td><td><span class="badge text-bg-primary">{{ ucfirst($lead->status) }}</span></td><td><span class="badge {{ $lead->score >= 80 ? 'text-bg-danger' : ($lead->score >= 60 ? 'text-bg-warning' : ($lead->score >= 40 ? 'text-bg-info' : 'text-bg-secondary')) }}">{{ $lead->score }} — {{ ucfirst($lead->temperature) }}</span></td><td>{{ $lead->next_follow_up_at?->format('d M Y H:i') ?? '—' }}</td><td class="text-end px-4"><a href="{{ route('leads.show',$lead) }}" class="btn btn-sm btn-outline-dark">View</a> <a href="{{ route('leads.edit',$lead) }}" class="btn btn-sm btn-outline-secondary">Edit</a></td></tr>@endforeach
</tbody></table></div><div class="p-3">{{ $leads->links() }}</div>
@else<div class="text-center py-5"><h5>No leads yet</h5><p class="text-muted">Create your first sales opportunity.</p><a href="{{ route('leads.create') }}" class="btn btn-dark">Add First Lead</a></div>@endif
</div></div></div>
@endsection