@extends('layouts.app')
@section('title',$lead->title.' | Lead')
@section('page_title','Lead Details')
@section('content')
<div class="container-fluid"><div class="d-flex justify-content-between align-items-start mb-4"><div><a href="{{ route('leads.index') }}" class="text-decoration-none text-muted">← Back to Leads</a><h2 class="fw-bold mt-3 mb-1">{{ $lead->title }}</h2><p class="text-muted mb-0"><a href="{{ route('companies.show',$lead->company) }}">{{ $lead->company->name }}</a>@if($lead->contact) · {{ $lead->contact->first_name }} {{ $lead->contact->last_name }}@endif</p></div><div class="d-flex gap-2"><a href="{{ route('ai-personalization.show',$lead) }}" class="btn btn-primary">AI Personalization</a><a href="{{ route('leads.edit',$lead) }}" class="btn btn-outline-dark">Edit</a><form method="POST" action="{{ route('leads.destroy',$lead) }}" onsubmit="return confirm('Delete this lead?');">@csrf @method('DELETE')<button class="btn btn-outline-danger">Delete</button></form></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="row g-4"><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Score</small><h2 class="fw-bold">{{ $lead->score }} <small class="fs-6 text-muted">/ 100</small></h2><span class="badge text-bg-primary">{{ ucfirst($lead->temperature) }}</span></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Status</small><h4 class="fw-bold">{{ ucfirst($lead->status) }}</h4><small class="text-muted">Lead Source: {{ $lead->leadSource?->name ?? 'Unspecified' }}</small><br><small class="text-muted">Source Detail: {{ $lead->source ?: 'None' }}</small></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Next Follow-up</small><h5 class="fw-bold">{{ $lead->next_follow_up_at?->format('d M Y H:i') ?? 'Not scheduled' }}</h5></div></div></div><div class="col-12"><div class="card border-0 shadow-sm"><div class="card-header bg-white border-0 py-3"><h5 class="fw-bold mb-0">Notes</h5></div><div class="card-body">{{ $lead->notes ?: 'No notes yet.' }}</div></div></div></div></div>
@endsection
