@extends('layouts.app')
@section('title','Lead Scoring | AI Receptionist')
@section('page_title','Lead Scoring')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Lead Scoring</h2><p class="text-muted mb-0">Set company intelligence signals and calculate lead priority.</p></div><form method="POST" action="{{ route('lead-scoring.run') }}">@csrf<button class="btn btn-dark">Recalculate All</button></form></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3"><h5 class="fw-bold mb-0">Company Intelligence Signals</h5></div><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Company</th><th>Signals</th><th>Current Score</th><th></th></tr></thead><tbody>
@forelse($companies as $company)<tr><td><strong>{{ $company->name }}</strong><br><small class="text-muted">{{ $company->industry ?: 'No industry' }}</small></td><td><form method="POST" action="{{ route('lead-scoring.company.signals',$company) }}" class="d-flex flex-wrap gap-2">@csrf @method('PATCH')
@foreach([['emergency_service','Emergency'],['appointment_based','Appointment'],['phone_prominent','Phone'],['online_booking','Online booking'],['small_team','Small team'],['outside_hours_service','Outside hours'],['high_value_service','High value'],['live_chat','Live chat'],['multiple_locations','Multi-location']] as [$field,$label])
<div class="form-check"><input class="form-check-input" type="checkbox" name="{{ $field }}" id="{{ $field }}_{{ $company->id }}" @checked($company->{$field})><label class="form-check-label small" for="{{ $field }}_{{ $company->id }}">{{ $label }}</label></div>
@endforeach</td><td><span class="badge {{ $company->lead_score >= 80 ? 'text-bg-danger' : ($company->lead_score >= 60 ? 'text-bg-warning' : ($company->lead_score >= 40 ? 'text-bg-info' : 'text-bg-secondary')) }}">{{ $company->lead_score }}/100</span></td><td><button class="btn btn-sm btn-outline-dark">Save & Score</button></form></td></tr>
@empty<tr><td colspan="4" class="text-center py-4 text-muted">No companies yet.</td></tr>@endforelse
</tbody></table></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white py-3"><h5 class="fw-bold mb-0">Lead Scores</h5></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="px-4">Lead</th><th>Company</th><th>Score</th><th>Temperature</th><th>Status</th></tr></thead><tbody>
@forelse($leads as $lead)<tr><td class="px-4"><a href="{{ route('leads.show',$lead) }}" class="fw-semibold text-decoration-none">{{ $lead->title }}</a></td><td>{{ $lead->company->name }}</td><td><span class="badge {{ $lead->score >= 80 ? 'text-bg-danger' : ($lead->score >= 60 ? 'text-bg-warning' : ($lead->score >= 40 ? 'text-bg-info' : 'text-bg-secondary')) }}">{{ $lead->score }}/100</span></td><td>{{ ucfirst($lead->temperature) }}</td><td>{{ ucfirst($lead->status) }}</td></tr>@empty<tr><td colspan="5" class="text-center py-5 text-muted">No leads to score.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $leads->links() }}</div></div>
<div class="row g-3 mt-4"><div class="col-md-6"><div class="card border-0 shadow-sm"><div class="card-body"><h5 class="fw-bold">Scoring bands</h5><p class="mb-1"><strong>80–100:</strong> Hot</p><p class="mb-1"><strong>60–79:</strong> High</p><p class="mb-1"><strong>40–59:</strong> Medium</p><p class="mb-0"><strong>0–39:</strong> Low</p></div></div></div><div class="col-md-6"><div class="card border-0 shadow-sm"><div class="card-body"><h5 class="fw-bold">Rules</h5><p class="small mb-1">Emergency +15 · Appointment +15 · Phone +10</p><p class="small mb-1">Small team +10 · Outside hours +10 · High value +10</p><p class="small mb-1">Multi-location +5 · Online booking −10 · Live chat −5</p></div></div></div></div>
</div>
@endsection
